# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pinv_my <- function(Bg) {
    .Call(`_NRRR_pinv_my`, Bg)
}

rrr_my <- function(X, Y, r) {
    .Call(`_NRRR_rrr_my`, X, Y, r)
}

BLCD <- function(X, Y, Xl0, Yl0, Ag0, Bg0, Al0, Bl0, n, r, d, p, rx, ry, jx, jy, maxiter, conv) {
    .Call(`_NRRR_BLCD`, X, Y, Xl0, Yl0, Ag0, Bg0, Al0, Bl0, n, r, d, p, rx, ry, jx, jy, maxiter, conv)
}

nrrr_init_my <- function(Y, X, r, rx, ry, jx, jy, p, d, n) {
    .Call(`_NRRR_nrrr_init_my`, Y, X, r, rx, ry, jx, jy, p, d, n)
}

nrrr_est_my <- function(Y, X, rini, r, rx, ry, jx, jy, p, d, n, maxiter, conv, method, lambda) {
    .Call(`_NRRR_nrrr_est_my`, Y, X, rini, r, rx, ry, jx, jy, p, d, n, maxiter, conv, method, lambda)
}

nrrr_select_my <- function(Y, X, xr, rfit, xrankfix, yrankfix, jx, jy, p, d, n, ic, maxiter, conv, method, lambda, dimred1, dimred2, dimred3) {
    .Call(`_NRRR_nrrr_select_my`, Y, X, xr, rfit, xrankfix, yrankfix, jx, jy, p, d, n, ic, maxiter, conv, method, lambda, dimred1, dimred2, dimred3)
}

del_rows <- function(X, e) {
    .Call(`_NRRR_del_rows`, X, e)
}

nrrr_cv_my <- function(Y, X, norder, nfold, xr, rfit, xrankfix, yrankfix, jx, jy, p, d, n, maxiter, method, dimred1, dimred2, dimred3, conv, lambda) {
    .Call(`_NRRR_nrrr_cv_my`, Y, X, norder, nfold, xr, rfit, xrankfix, yrankfix, jx, jy, p, d, n, maxiter, method, dimred1, dimred2, dimred3, conv, lambda)
}

